### ISSUE TITLE
STDWEB_PRIVATE will be null if use stdweb only from other crate (0.4.0)

### ISSUE THREAD

**Issue by edwin0cheng** [koute/stdweb#135] opened 2018-02-24 16:15 UTC
I just updated my project to use 0.4.0 and found that if my main crate only use stdweb from other crate, (i.e the main crate itself do not depend on stdweb, but it depend on a crate which is depends on stdweb)

when run it in browser, it will fail : 
```
Error loading Rust wasm module 'unigame': TypeError: Cannot read property 'from_js' of undefined
```
but It works in 0.3.

**Comment by koute** [comment] 2018-02-24 19:36
Hm, it works for me.

1. How are you compiling your project? Are you using `cargo-web`?
2. Can you post a minimal reproduction?

**Comment by edwin0cheng** [comment] 2018-02-24 19:59
1. yes
2. Here is ; 
https://github.com/edwin0cheng/stdweb-issue-135

**Comment by edwin0cheng** [comment] 2018-02-24 20:02
It seem like to because this line in other-lib cargo.toml : 
[target.'cfg(target_arch = "wasm32")'.dependencies]

**Comment by koute** [comment] 2018-02-24 20:08
Hmm... ah, yes, I know what is the problem.

For now you can replace your

```
[target.'cfg(target_arch = "wasm32")'.dependencies]
```

with

```
[target.wasm32-unknown-unknown.dependencies]
```

and it will work.

Thanks for the report!

**Comment by koute** [comment] 2018-02-24 20:09
Since this is a `cargo-web` issue I'm going to close this; however I opened up a new issue in `cargo-web` repository.

**Closed by koute** 2018-02-24 20:09 UTC
