### ISSUE TITLE
Error when build examples/webgl

### ISSUE THREAD

**Issue by smallnewer** [koute/stdweb#188] opened 2018-04-06 09:08 UTC
````
$> cargo web build --target=wasm32-unknown-unknown

...
...
...

error: failed to run custom build command for `webgl v0.1.0 (file:///Applications/XAMPP/xamppfiles/htdocs/rust/stdweb/examples/webgl)`
process didn't exit successfully: `/Applications/XAMPP/xamppfiles/htdocs/rust/stdweb/examples/target/release/build/webgl-2aae80b3fefdd57c/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
error: build failed
````

But `examples/canvas` build success.

**Comment by koute** [comment] 2018-04-06 22:32
It it reproducible every time? What's your version of Rust? Your OS?

cc @Diggsey

**Comment by smallnewer** [comment] 2018-04-07 02:34
I tried it for the first time yesterday..

Rust version: `rustc 1.27.0-nightly (48fa6f963 2018-04-05)`
Code version: `fc7b3c1e7b68a82ceffb2126770514139987116c`
OS: Mac EI Caption

**Comment by koute** [comment] 2018-04-18 19:19
Unfortunately there isn't anything I can do about this since I don't even have access to an OS X machine; probably the best way to debug this would be to just try to move the build script into a standalone binary, compile in debug mode, hook `gdb` to it and see why it crashes.

**Comment by Thomspoon** [comment] 2018-06-13 14:29
I verified the same as @srenatus on High Sierra. Could not reproduce the error.

**Comment by koute** [comment] 2018-06-29 22:02
Since it's not reproducible I'm closing this for now; if someone manages to reproduce feel free to reopen.

**Closed by koute** 2018-06-29 22:02 UTC
Labels: help wanted
